name: CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  generate-doxygen-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt update && sudo apt install -y graphviz

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Node dependencies
        run: npm install

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Compile project for Windows using CMake
        run: cmake --preset windows-release && cmake --build --preset windows-release-build

      - name: Compile project for Linux using CMake
        run: cmake --preset linux-release && cmake --build --preset linux-release-build

      - name: Prepare build artifacts
        run: cp ./build/linux-release/DoublyLinkedList ./DoublyLinkedList-${{ steps.tag_version.outputs.new_tag }}-linux-x64 \
             cp ./build/windows-release/DoublyLinkedList.exe ./DoublyLinkedList-${{ steps.tag_version.outputs.new_tag }}-win-x64.exe

      - name: Set version number in Doxyfile
        run: echo "PROJECT_NUMBER         = \"${{ steps.tag_version.outputs.new_tag }}\"" >> Doxyfile

      - name: Generate Doxygen Documentation
        uses: mattnotmitt/doxygen-action@edge
        with:
          enable-latex: true

      - name: Deploy Doxygen documentation website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doxygen/html

      - name: Prepare Doxygen PDF file
        run: cp ./docs/doxygen/latex/refman.pdf ./Dokumentacja-Doxygen.pdf

      - name: Compile LaTeX documentation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ./docs/dokument.tex

      - name: Prepare LaTeX PDF file
        run: cp ./docs/dokument.pdf ./Dokumentacja.pdf

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: DoublyLinkedList-${{ steps.tag_version.outputs.new_tag }}-linux-x64,DoublyLinkedList-${{ steps.tag_version.outputs.new_tag }}-win-x64.exe,Dokumentacja.pdf,Dokumentacja-Doxygen.pdf
